<!DOCTYPE html>
<html lang="fr" prefix="og: https://ogp.me/ns#">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Home</title>
      <link rel="stylesheet" href="assets/style/css/style.css">
    </head>
    <body>
        <main>
            <h1>Home de page</h1>
            <form method="get" action="index.php">
                <fieldset>
                    <label for="route">Choississez votre chemin :</label>
                    <select name="route" id="route">
                        <option value="">
                            ---------  Choississez ---------
                        </option>
                        <option value="about">
                            Page About
                        </option>
                        <option value="contact">
                            Page Contact
                        </option>
                    </select>
                </fieldset>
                <button type="submit">Envoyer</button>
            </form>
        </main>
    </body>
</html>